RollingPlayerGUI = CreateFrame("Frame", "Rolling_Frame", UIParent, "BasicFrameTemplateWithInset")
RollingPlayerGUI:ClearAllPoints()
RollingPlayerGUI:SetSize(300, 230)
RollingPlayerGUI:SetPoint("CENTER", UIParent, "CENTER")
RollingPlayerGUI:SetMovable(true)
RollingPlayerGUI:EnableMouse(true)
RollingPlayerGUI:SetUserPlaced(true)
RollingPlayerGUI:SetScript("OnMouseDown", fr.StartMoving)
RollingPlayerGUI:SetScript("OnMouseUp", function (self)
    RollingPlayerGUI:StopMovingOrSizing()
    RollingI.XPosFrame = self:GetLeft()
    RollingI.YPosFrame = self:GetBottom()
end)
RollingPlayerGUI:SetScript("OnHide", function (self)
	RollingPlayerFrame = false
end)
RollingPlayerGUI:SetScript("OnShow", function (self)
	RollingPlayerFrame = true
end)

RollingPlayerGUI.roll = CreateFrame("Button", nil, RollingPlayerGUI, "GameMenuButtonTemplate")
RollingPlayerGUI.roll:SetPoint("Right", RollingPlayerGUI, "TOP", 130, -200)
RollingPlayerGUI.roll:SetSize(260, 20)
RollingPlayerGUI.roll:SetText("/Roll")
RollingPlayerGUI.roll:RegisterForClicks("AnyUp")
RollingPlayerGUI.roll:SetScript("OnMouseDown", function(self) 
	RandomRoll(1,100)
end)

RollingPlayerGUI.text = RollingPlayerGUI:CreateFontString(nil, "ARTWORK")
RollingPlayerGUI.text:SetFont("Fonts\\ARIALN.ttf", 18, "OUTLINE")
RollingPlayerGUI.text:SetPoint("TOPLEFT", 10, -80)
RollingPlayerGUI.text:SetJustifyH("LEFT")

RollingPlayerGUI.item = RollingPlayerGUI:CreateFontString(nil, "ARTWORK")
RollingPlayerGUI.item:SetFont("Fonts\\ARIALN.ttf", 16, "OUTLINE")
RollingPlayerGUI.item:SetPoint("TOPLEFT", 50, -38)
RollingPlayerGUI.item:SetJustifyH("LEFT")

RollingPlayerGUI.icon = CreateFrame("Button", nil, RollingPlayerGUI, "GameMenuButtonTemplate")
RollingPlayerGUI.icon:SetPoint("Right", RollingPlayerGUI, "TOP", -100, -55)
RollingPlayerGUI.icon:SetSize(40, 40)
RollingPlayerGUI.icon.overlay = RollingPlayerGUI.icon:CreateTexture(nil, "OVERLAY")
RollingPlayerGUI.icon.overlay:SetPoint("Right", RollingPlayerGUI, "TOP", -100, -55)
RollingPlayerGUI.icon.overlay:SetSize(40, 40)
RollingPlayerGUI.icon.overlay:SetTexture(GetItemIcon(6948))
RollingPlayerGUI.icon:SetScript("OnEnter", function(self) 
	GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
	GameTooltip:ClearLines()
	--local id = GetItemInfoInstant(item)
	if Rolling["Page"]["roll"]["Item"] then
		local _, id = GetItemInfo(tostring(Rolling["Page"]["roll"]["Item"]))
		--GameTooltip:SetItemByID(id)
		GameTooltip:SetHyperlink(id)
	else
		local _, id = GetItemInfo("Ruhestein")
		GameTooltip:SetHyperlink(id)
	end
	GameTooltip:Show() 
end)
RollingPlayerGUI.icon:SetScript("OnLeave", function(self) GameTooltip:Hide() end)
RollingPlayerGUI.icon:Show()

RollingPlayerGUI:Hide()